import dev1 from './devpng.png'
import dev2 from './dev2png.png'
import skillpng from './skillspng.png'
import workpng from './workpng.png'
import aboutme from './aboutmepng.png'
import sec1 from './screenshot4.png'
import sec2 from './screenshot1.png'
import sec3 from './screenshot2.png'
import sec4 from './screenshot3.png'
import bg1 from './bg1.png'
import bg2 from './bg2.png'
import bg3 from './bg3.png'
import bg4 from './bg4.png'
import bg5 from './bg5.png'
export {dev1, dev2, skillpng, workpng, aboutme, sec1, sec2, sec3, sec4, bg1, bg2 , bg3, bg4, bg5}